name 'elasticsearch_opsworks'
maintainer 'Edwin Hermans'
maintainer_email 'edwin@madtech.cx'
license 'All rights reserved'
description 'Installs/Configures elasticsearch-opsworks'
long_description 'Installs/Configures elasticsearch-opsworks'
version '0.3.4'

depends 'apt', '~> 2.9.0'
depends 'apt-docker', '~> 0.3.0'
depends 'docker', '~> 2.5.0'
depends 'elasticsearch', '~> 2.2.0'
depends 'java', '~> 1.39.0'
depends 'monitor'
depends 'nginx', '~> 2.7.0'
